  production: 
   adapter: mysql2
   encoding: utf8 
   database: parkingbuddy 
   host: localhost
   username: ror 
   password: 123 
   reconnect: true

  development:   
   adapter: mysql2
   encoding: utf8 
   database: parkingbuddy 
   host: localhost
   username: ror 
   password: 123 
   reconnect: true

   test: 
   adapter: mysql2
   encoding: utf8 
   database: parkingbuddy 
   host: localhost
   username: ror 
   password: 123 
   reconnect: true